// vPS specific hardware file

#include <si5351.h> // https://github.com/tmr4/Si5351_T41

#include "..\SDT.h"

#include "..\calibrate.h"
#include "..\Tune.h"

//-------------------------------------------------------------------------------------------------------------
// Data
//-------------------------------------------------------------------------------------------------------------

Si5351 si5351;

//-------------------------------------------------------------------------------------------------------------
// Code
//-------------------------------------------------------------------------------------------------------------

FLASHMEM void InitSI5351() {
  si5351.reset();
  si5351.init(SI5351_CRYSTAL_LOAD_10PF, Si_5351_crystal, freqCorrectionFactor);
  si5351.set_ms_source(SI5351_CLK2, SI5351_PLLB); //  Allows CLK1 and CLK2 to exceed 100 MHz simultaneously.
  si5351.drive_strength(SI5351_CLK1, SI5351_DRIVE_8MA);
  si5351.drive_strength(SI5351_CLK2, SI5351_DRIVE_8MA);
}

void SetSI5351FreqCorFactor(int factor) {
  si5351.set_correction(factor, SI5351_PLL_INPUT_XO);
  si5351.pll_reset(SI5351_PLLB);
  SetFreq(t41.CenterFreq);
}

/*****
  Purpose: Set si5351 frequency

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL

  *** TODO: RadioState needs cleaned up ***
*****/
void SetFreq(int freq, bool reset) {
  unsigned long long Clk1SetFreq, Clk2SetFreq;

  if(reset) return; // *** TODO: v11 isn't designed to reset.  Consider fix. ***

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LOT frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.
  Clk1SetFreq = (freq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(t41.RadioState == CW_TRANSMIT_STRAIGHT_STATE || t41.RadioState == CW_TRANSMIT_PADDLE_STATE || t41.RadioState == CW_TRANSMIT_KEYER_STATE) {
    if(t41.DemodMode == DEMOD_LSB) {
      Clk1SetFreq = (freq + CWFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
    } else {
      if(t41.DemodMode == DEMOD_USB) {
        Clk1SetFreq = (freq - CWFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  //  flip CWFreqShift, sign originally plus
      }
    }
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = ((t41.CenterFreq + t41.IntermediateFreq) * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(t41.RadioState == RECEIVE_STATE) {   //  Receive state
    si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
    si5351.output_enable(SI5351_CLK1, 0);  // CLK1 (transmit) off during receive to prevent birdies
    si5351.output_enable(SI5351_CLK2, 1);
  }

  if(t41.RadioState == SSB_TRANSMIT_STATE || t41.RadioState == CW_TRANSMIT_STRAIGHT_STATE || t41.RadioState == CW_TRANSMIT_PADDLE_STATE || t41.RadioState == CW_TRANSMIT_KEYER_STATE || t41.RadioState == DATA_TRANSMIT_STATE) {  // Transmit state
    si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
    si5351.output_enable(SI5351_CLK2, 0);  // CLK2 (receive) off during transmit to prevent spurious outputs
    si5351.output_enable(SI5351_CLK1, 1);
  }
}

/*****
  Activates both RX and TX oscilators

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL
*****/
FLASHMEM void SetFreqCal(long calFreqShift) {
  int TxRxFreq = t41.ActiveFreq();

  unsigned long long Clk1SetFreq = (TxRxFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;
  unsigned long long Clk2SetFreq;

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LO frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.

  if(t41.DemodMode == DEMOD_LSB) {
    //Clk1SetFreq = (TxRxFreq + CWFreqShift + calFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
    Clk1SetFreq = (TxRxFreq + calFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
  } else if(t41.DemodMode == DEMOD_USB || t41.DemodMode == DEMOD_FT8) {
    //Clk1SetFreq = (TxRxFreq - CWFreqShift - calFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally plus
    Clk1SetFreq = (TxRxFreq - calFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally plus
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = (t41.CenterFreq  + t41.IntermediateFreq) * SI5351_FREQ_MULT * MASTER_CLK_MULT;

  //  Set and enable both RX and TX local oscillator outputs.
  si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
  si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
  si5351.output_enable(SI5351_CLK2, 1);
  si5351.output_enable(SI5351_CLK1, 1);

}
