// vPS specific hardware file

#include <si5351.h> // https://github.com/tmr4/Si5351_T41

#include "..\SDT.h"

#include "..\Tune.h"

//-------------------------------------------------------------------------------------------------------------
// Data
//-------------------------------------------------------------------------------------------------------------

extern Si5351 si5351;

//-------------------------------------------------------------------------------------------------------------
// Code
//-------------------------------------------------------------------------------------------------------------

/*****
  Purpose: Set si5351 frequency

  CAUTION: SI5351_FREQ_MULT is set in the si5253.h header file and is 100UL
*****/
void SetFreq(bool reset) {
  unsigned long long Clk1SetFreq, Clk2SetFreq;

  if(reset) return; // *** TODO: v11 isn't designed to reset.  Consider fix. ***

  // NEVER USE AUDIONOINTERRUPTS HERE: that introduces annoying clicking noise with every frequency change
  // SI5351_FREQ_MULT is 100ULL, MASTER_CLK_MULT is 4;

  // The SSB LO frequency is always the same as the displayed transmit frequency.
  // The CW LOT frequency must be shifted by 750 Hz due to the way the CW carrier is generated by a quadrature tone.
  Clk1SetFreq = (TxRxFreq * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(radioState == CW_TRANSMIT_STRAIGHT_STATE || radioState == CW_TRANSMIT_KEYER_STATE) {
    if(currentDemodMode == DEMOD_LSB) {
      Clk1SetFreq = (TxRxFreq + CWFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  // flip CWFreqShift, sign originally minus
    } else {
      if(currentDemodMode == DEMOD_USB) {
        Clk1SetFreq = (TxRxFreq - CWFreqShift) * SI5351_FREQ_MULT * MASTER_CLK_MULT;  //  flip CWFreqShift, sign originally plus
      }
    }
  }

  //  The receive LO frequency is not dependent on mode or sideband.  CW frequency shift is done in DSP code.
  Clk2SetFreq = ((centerFreq + intermediateFreq) * SI5351_FREQ_MULT) * MASTER_CLK_MULT;

  if(radioState == SSB_RECEIVE_STATE || radioState == CW_RECEIVE_STATE || radioState == DATA_RECEIVE_STATE) {   //  Receive state
    si5351.set_freq(Clk2SetFreq, SI5351_CLK2);
    si5351.output_enable(SI5351_CLK1, 0);  // CLK1 (transmit) off during receive to prevent birdies
    si5351.output_enable(SI5351_CLK2, 1);
  }

  if(radioState == SSB_TRANSMIT_STATE || radioState == CW_TRANSMIT_STRAIGHT_STATE || radioState == CW_TRANSMIT_KEYER_STATE || radioState == DATA_TRANSMIT_STATE) {  // Transmit state
    si5351.set_freq(Clk1SetFreq, SI5351_CLK1);
    si5351.output_enable(SI5351_CLK2, 0);  // CLK2 (receive) off during transmit to prevent spurious outputs
    si5351.output_enable(SI5351_CLK1, 1);
  }
}
